version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5050:5050"
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: p1ssw0rd
      DB_DATABASE: local-mysql

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pa
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
